<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="2" ignored="0" total="13" passed="9" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-04-09T15:26:31 IST" name="Suite" finished-at="2025-04-09T15:27:08 IST" duration-ms="37062">
    <groups>
    </groups>
    <test started-at="2025-04-09T15:26:31 IST" name="Test" finished-at="2025-04-09T15:27:08 IST" duration-ms="37062">
      <class name="Tests.Regression">
        <test-method is-config="true" signature="Launch_website()[pri:0, instance:Tests.Regression@3cfdd820]" started-at="2025-04-09T15:26:31 IST" name="Launch_website" finished-at="2025-04-09T15:26:52 IST" duration-ms="20778" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Launch_website -->
        <test-method signature="validate_date()[pri:2, instance:Tests.Regression@3cfdd820]" started-at="2025-04-09T15:26:52 IST" name="validate_date" finished-at="2025-04-09T15:26:53 IST" duration-ms="451" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_date -->
        <test-method signature="alert_handling()[pri:3, instance:Tests.Regression@3cfdd820]" started-at="2025-04-09T15:26:53 IST" name="alert_handling" finished-at="2025-04-09T15:26:55 IST" duration-ms="1993" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- alert_handling -->
        <test-method signature="switch_window()[pri:5, instance:Tests.Regression@3cfdd820]" started-at="2025-04-09T15:26:55 IST" name="switch_window" finished-at="2025-04-09T15:26:57 IST" duration-ms="2142" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- switch_window -->
        <test-method is-config="true" signature="quit_browser()[pri:0, instance:Tests.Regression@3cfdd820]" started-at="2025-04-09T15:26:57 IST" name="quit_browser" finished-at="2025-04-09T15:27:06 IST" duration-ms="9059" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit_browser -->
      </class> <!-- Tests.Regression -->
      <class name="Tests.DataValidation">
        <test-method is-config="true" signature="Launch_website()[pri:0, instance:Tests.DataValidation@2f666ebb]" started-at="2025-04-09T15:26:31 IST" name="Launch_website" finished-at="2025-04-09T15:26:57 IST" duration-ms="25804" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Launch_website -->
        <test-method signature="validate_country_name(java.util.HashMap)[pri:1, instance:Tests.DataValidation@2f666ebb]" started-at="2025-04-09T15:26:58 IST" name="validate_country_name" data-provider="getData" finished-at="2025-04-09T15:27:01 IST" duration-ms="2584" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Country=India, Tickets=3}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_country_name -->
        <test-method signature="validate_country_name(java.util.HashMap)[pri:1, instance:Tests.DataValidation@2f666ebb]" started-at="2025-04-09T15:27:01 IST" name="validate_country_name" data-provider="getData" finished-at="2025-04-09T15:27:03 IST" duration-ms="2325" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Country=Germany, Tickets=4}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_country_name -->
        <test-method signature="validate_country_name(java.util.HashMap)[pri:1, instance:Tests.DataValidation@2f666ebb]" started-at="2025-04-09T15:27:03 IST" name="validate_country_name" data-provider="getData" finished-at="2025-04-09T15:27:05 IST" duration-ms="1928" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Country=China, Tickets=2}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_country_name -->
        <test-method signature="add_entries(java.util.HashMap)[pri:2, instance:Tests.DataValidation@2f666ebb]" started-at="2025-04-09T15:27:05 IST" name="add_entries" data-provider="getData" finished-at="2025-04-09T15:27:06 IST" duration-ms="1316" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Country=India, Tickets=3}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- add_entries -->
        <test-method signature="add_entries(java.util.HashMap)[pri:2, instance:Tests.DataValidation@2f666ebb]" started-at="2025-04-09T15:27:06 IST" name="add_entries" data-provider="getData" finished-at="2025-04-09T15:27:07 IST" duration-ms="928" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Country=Germany, Tickets=4}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- add_entries -->
        <test-method signature="add_entries(java.util.HashMap)[pri:2, instance:Tests.DataValidation@2f666ebb]" started-at="2025-04-09T15:27:07 IST" name="add_entries" data-provider="getData" finished-at="2025-04-09T15:27:08 IST" duration-ms="762" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Country=China, Tickets=2}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- add_entries -->
        <test-method is-config="true" signature="quit_browser()[pri:0, instance:Tests.DataValidation@2f666ebb]" started-at="2025-04-09T15:27:08 IST" name="quit_browser" finished-at="2025-04-09T15:27:08 IST" duration-ms="402" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit_browser -->
      </class> <!-- Tests.DataValidation -->
      <class name="Tests.ErrorValidation">
        <test-method is-config="true" signature="Launch_website()[pri:0, instance:Tests.ErrorValidation@19976a65]" started-at="2025-04-09T15:26:31 IST" name="Launch_website" finished-at="2025-04-09T15:26:53 IST" duration-ms="21911" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Launch_website -->
        <test-method retried="true" signature="validate_country_name(java.util.HashMap)[pri:0, instance:Tests.ErrorValidation@19976a65]" started-at="2025-04-09T15:26:53 IST" name="validate_country_name" data-provider="Data" finished-at="2025-04-09T15:26:56 IST" duration-ms="2643" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Country=Indian, Tickets=3}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [null] but found [Indian]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [null] but found [Indian]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Tests.ErrorValidation.validate_country_name(ErrorValidation.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_country_name -->
        <test-method signature="validate_country_name(java.util.HashMap)[pri:0, instance:Tests.ErrorValidation@19976a65]" started-at="2025-04-09T15:26:56 IST" name="validate_country_name" data-provider="Data" finished-at="2025-04-09T15:26:58 IST" duration-ms="2178" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Country=Indian, Tickets=3}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [null] but found [Indian]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [null] but found [Indian]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Tests.ErrorValidation.validate_country_name(ErrorValidation.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_country_name -->
        <test-method retried="true" signature="validate_country_name(java.util.HashMap)[pri:0, instance:Tests.ErrorValidation@19976a65]" started-at="2025-04-09T15:26:59 IST" name="validate_country_name" data-provider="Data" finished-at="2025-04-09T15:27:01 IST" duration-ms="2899" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Country=USA, Tickets=5}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [null] but found [USA]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [null] but found [USA]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Tests.ErrorValidation.validate_country_name(ErrorValidation.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_country_name -->
        <test-method signature="validate_country_name(java.util.HashMap)[pri:0, instance:Tests.ErrorValidation@19976a65]" started-at="2025-04-09T15:27:01 IST" name="validate_country_name" data-provider="Data" finished-at="2025-04-09T15:27:04 IST" duration-ms="2915" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Country=USA, Tickets=5}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [null] but found [USA]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [null] but found [USA]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Tests.ErrorValidation.validate_country_name(ErrorValidation.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_country_name -->
        <test-method is-config="true" signature="quit_browser()[pri:0, instance:Tests.ErrorValidation@19976a65]" started-at="2025-04-09T15:27:05 IST" name="quit_browser" finished-at="2025-04-09T15:27:06 IST" duration-ms="1494" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit_browser -->
      </class> <!-- Tests.ErrorValidation -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
